spring:
  application:
    name: Trends
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://docker-prac.cj6u4kmew97i.ap-northeast-2.rds.amazonaws.com:3306/test
    username: root
    password: Esc141414!

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000


springdoc:
  show-login-endpoint: true